### ISSUE TITLE
add glob support for game thumbnails

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/rocat#62]
It would be nice to support globs for game thumbnails:

```yml
templates:
  experience:
    thumbnails:
      - marketing/thumbnails/*
```

The files should be sorted alphabetically so that ordering is consistent between deploys, and to enable developers to arrange their thumbnails in order.
